services:
  users-service-db:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users-service
    volumes:
      - users-service-db-data:/var/lib/postgresql/data
    networks:
      - payflow-network
  sales-service-db:
    image: postgres:18-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales-service
    volumes:
      - sales-service-db-data:/var/lib/postgresql/data
    networks:
      - payflow-network
  inventory-service-db:
    image: postgres:18-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory-service
    volumes:
      - inventory-service-db-data:/var/lib/postgresql/data
    networks:
      - payflow-network
  broker:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
    - broker-data:/var/lib/rabbitmq
    networks:
      - payflow-network

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # UI
      - "6831:6831/udp" # Traces UDP
      - "14268:14268" # Traces HTTP
      - "4318:4318" # OTLP/HTTP
    networks:
      - payflow-network

volumes:
  users-service-db-data:
  sales-service-db-data:
  inventory-service-db-data:
  broker-data:

networks:
  payflow-network:
    driver: bridge